export const MESSAGE_TYPE_INPUT: string = 'INPUT';
export const MESSAGE_TYPE_OUTPUT: string = 'OUTPUT';
export const MESSAGE_TYPE_OTHERS: string = 'OTHERS';
export const MESSAGE_TAG_LEADER: string = 'LEADER';
export const MESSAGE_TAG_UI_MAKER: string = 'UIMAKER';
export const MESSAGE_TYPE_CONTROL_CLEAR: string = 'CONTROL.CLEAR';
export const MESSAGE_TYPE_TASK_CREATE_UI: string = 'TASK.CREATE.UI';
export const MESSAGE_TYPE_TASK_RESULT_UI: string = 'TASK.RESULT.UI';
